Add missing "endpoint_auto_confirms = true" argument
Otherwise you get an error:

  Error: Protocol http/https is only supported for endpoints which auto confirms!